
services:
  postgres:
    image: postgres:16
    container_name: payme-postgres
    environment:
      POSTGRES_DB: payme
      POSTGRES_USER: payme
      POSTGRES_PASSWORD: payme
    ports:
      - "5432:5432"
    volumes:
      - payme_pgdata:/var/lib/postgresql/data

volumes:
  payme_pgdata:
